### ISSUE TITLE
Only allow branches to be changed via pull requests

### ISSUE THREAD

**Issue by Jayman2000** [mxd1760/song-typing#8]
@mxd1760 expressed interest in becoming better at working on software in a team (as opposed to working on software solo). One way to accomplish that goal is to prevent contributors from pushing to the `main` branch and require that changes to the main branch have to be made via pull requests. You can do that by creating a [ruleset](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) for the repository. I propose that we use this ruleset:

![The ruleset is titled “Changes must be made in approved pull requests”. Its enforcement status is “Active”. The bypass list is empty. The ruleset targets all branches except for branches that match this pattern: pr/\*\*. The ruleset has the “Restrict creations”, “Restrict updates”, “Require a pull request before merging” and “Block force pushes” rules enabled. The “Require pull request before merging” rule has some additional settings enabled. Specifically, its “Required approvals” setting is set to 1 and its “Require approval of the most recent reviewable push” setting is turned on.](https://github.com/user-attachments/assets/9149730f-787f-4c5b-bd52-426bdd24a9a5)

That ruleset will force us to review each others contributions before the contributions get accepted. By forcing us to review each others contributions, the ruleset will force us to communicate and make compromises with each other.  I think that communication and compromises are an important part of working as a team.

If we decide to use that ruleset, then we can import it into this repo by using this JSON:

```json
{
  "id": 2156328,
  "name": "Changes must be made in approved pull requests",
  "target": "branch",
  "source_type": "Repository",
  "source": "Jayman2000/Jayman2000",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "exclude": [
        "refs/heads/pr/**"
      ],
      "include": [
        "~ALL"
      ]
    }
  },
  "rules": [
    {
      "type": "deletion"
    },
    {
      "type": "non_fast_forward"
    },
    {
      "type": "update"
    },
    {
      "type": "pull_request",
      "parameters": {
        "required_approving_review_count": 1,
        "dismiss_stale_reviews_on_push": false,
        "require_code_owner_review": false,
        "require_last_push_approval": true,
        "required_review_thread_resolution": false
      }
    },
    {
      "type": "creation"
    }
  ],
  "bypass_actors": []
}
```

(The JSON for this ruleset is dedicated to the public domain using [🅭🄍1.0](https://creativecommons.org/publicdomain/zero/1.0).)

---

There are two things that we need to be aware of if we adopt that ruleset, though.

1. When owner of this repository makes a new branch for a pull request, the branch’s name has to start with “pr/”. This only applies to the repository owner, though. Other contributors can still create branches in their forks like usual.

2. If you we ever want to create a branch that isn’t for a pull request, then we’ll have to temporarily disable this ruleset.

**Comment by mxd1760** [comment]
Should I close this issue now that the repo is public?

**Comment by Jayman2000** [comment]
Yes.
